// Re-export all types and constants from the shared module
export type {
  Priority,
  ColumnId,
  AgentStatus,
  AgentType,
  AgentInfo,
  Worker,
  WorkerStatus,
  WorkerUsageTotals,
  WorkerUsageTask,
  WorkerUsageProject,
  WorkerUsageWorker,
  WorkerUsageReport,
  Project,
  ProjectTaskCounts,
  ProjectConfig,
  ProjectPathValidation,
  CreateProjectRequest,
  UpdateProjectRequest,
  Task,
  TaskAttachment,
  TaskGroup,
  TaskTemplate,
  AgentEventType,
  AgentEvent,
  AgentEventImportance,
  ClarificationRequestPayload,
  TaskClarificationRequest,
  TaskClarificationAnswer,
  Column,
  WSMessage,
  ImportResult,
  A2AWorkflowRole,
  WorkflowPhase,
  A2AAgentProjectAccess,
  A2ASkill,
  A2AAgent,
} from '../../../../shared/types.js';

export { classifyAgentEventImportance } from '../../../../shared/types.js';
export { VALID_TRANSITIONS, MAX_GROUP_CHILDREN, MIN_GROUP_CHILDREN } from '../../../../shared/constants.js';
