// Re-export all types and validation utilities from the shared module
export type {
  AgentInfo,
  Priority,
  ColumnId,
  AgentStatus,
  AgentType,
  Task,
  WorkerTaskAssignment,
  Worker,
  TaskProvenance,
  ClarificationRequestPayload,
  TaskClarificationRequest,
  TaskClarificationAnswer,
  TaskGroup,
  TaskTemplate,
  TaskAttachment,
  ImportResult,
  Project,
  ProjectTaskCounts,
  ProjectConfig,
  CreateProjectRequest,
  UpdateProjectRequest,
  AgentEvent,
  AgentEventType,
  AgentEventImportance,
  A2AWorkflowRole,
  WorkflowPhase,
  A2AAgentProjectAccess,
  A2ASkill,
  A2AAgent,
  WSMessage,
} from '@ai-agent-board/shared/types.js';

export {
  VALID_TRANSITIONS,
  VALID_AGENT_STATUS_TRANSITIONS,
  isValidPriority,
  isValidColumnId,
  isValidAgentStatus,
  isValidAgentType,
  canTransitionAgentStatus,
  MAX_GROUP_CHILDREN,
  MIN_GROUP_CHILDREN,
} from '@ai-agent-board/shared/constants.js';

export { classifyAgentEventImportance } from '@ai-agent-board/shared/types.js';
